### ISSUE TITLE
App Features and Tasks

### ISSUE THREAD

**Issue by shavenking** [andytsai-shaven/project-boomer#6]
## Foundations
- [x] #4 Implement layouts.
## User can create workflows in settings.
- [x] #7 Design data schema.
- [x] #9 Implement migrations and factories.
- [x] #13 Design routes.
- [x] #8 Implement API tests.
- [x] #10 Implement APIs.
- [x] #12 Implement views.
- [x] #11 Implement React components.
